### ISSUE TITLE
Hide and Seek

### ISSUE THREAD

**Issue by dgsierra** [MarcoOquendoC/Portfolio#11]
Hi @MarcoOquendoC 👍 

## Nice Job!!

https://giphy.com/embed/sTczweWUTxLqg

There is a error that dont let the user close the menu on movil version, i think it could be solved with replacing the line 30 `about.addEventListener('click', openMenu);` with `about.addEventListener('click', closeMenu);`

**Comment by MarcoOquendoC** [comment]
# Hi @dgonzalesi,

Thank you I will be fixing it ASAP.
