### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Aseadd** [MarcoOquendoC/Portfolio#4]
### Comments to be addressed 

Well done ✅ 
![clap-leonardo-de-caprio](https://user-images.githubusercontent.com/48018471/177798994-23d037b0-95fb-407d-84b2-615bb8beae0e.gif)

- Please use **ID** selector instead of **class** for single block tags like p
- Use comments inside your HTML code to increase readability

**Comment by MarcoOquendoC** [comment]
Thank you.

Features were updated.
