### ISSUE TITLE
peer-to-peer code review for marco's portfolio

### ISSUE THREAD

**Issue by haftamudesta** [MarcoOquendoC/Portfolio#7]
1. The background URL links in the styles file should follow the correct semantics
2. Please kindly include hover effects in your project

**Comment by MarcoOquendoC** [comment]
# Hello, there,

## Issues corrected. 
Thanks for your feedback

![giphy](https://user-images.githubusercontent.com/104022866/178586773-e88dca4c-095f-4397-80cf-f44d43e88c46.gif)
